#!/usr/bin/env python3

# food inspections data
# download as .csv file, original name Food_Inspections.csv
# Put in data/input/Food_Inspections.csv
# 174 Mb
# fields
# Inspection ID,DBA Name,AKA Name,License #,Facility Type,Risk,Address,City,State,Zip,Inspection Date,Inspection Type,Results,Violations,Latitude,Longitude,Location
# example rows
# 1990078,THE DUGOUT,THE DUGOUT,2492994,Restaurant,Risk 2 (Medium),950 W ADDISON ST ,CHICAGO,IL,60613,03/03/2017,License Re-Inspection,Pass,"2. FACILITIES TO MAINTAIN PROPER TEMPERATURE - Comments: REACH IN COOLER AT 31.4F. | 16. FOOD PROTECTED DURING STORAGE, PREPARATION, DISPLAY, SERVICE AND TRANSPORTATION - Comments: BARRIER PROVIDED FOR BAR. ICE MACHINE CLEANED AT LOWER LEVEL KITCHEN. | 18. NO EVIDENCE OF RODENT OR INSECT OUTER OPENINGS PROTECTED/RODENT PROOFED, A WRITTEN LOG SHALL BE MAINTAINED AVAILABLE TO THE INSPECTORS - Comments: FRONT DOOR RODENT PROOFED AT BOTTOM. | 30. FOOD IN ORIGINAL CONTAINER, PROPERLY LABELED: CUSTOMER ADVISORY POSTED AS NEEDED - Comments: NO CONSUMER ADVISORY POSTED REGARDING CONSUMPTION OF UNDERCOOKED ANIMAL FOODS. MUST POST. | 34. FLOORS: CONSTRUCTED PER CODE, CLEANED, GOOD REPAIR, COVING INSTALLED, DUST-LESS CLEANING METHODS USED - Comments: FOUND NO BASE COVING BELOW BAR 1ST FLOOR. MUST PROVIDE. FOUND MISSING FLOOR TILE AT MAIN KITCHEN BY COOKING EQUIPMENT. MUST REPLACE. | 35. WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTRUCTED PER CODE: GOOD REPAIR, SURFACES CLEAN AND DUST-LESS CLEANING METHODS - Comments: FOUND WALL BEHIND MAIN BAR NOT EASY TO CLEAN. MUST SEAL TO BE EASILY CLEANABLE. ALSO, FOUND SOME HOLES ON SAME WALL THAT MUST BE SEALED. | 38. VENTILATION: ROOMS AND EQUIPMENT VENTED AS REQUIRED: PLUMBING: INSTALLED AND MAINTAINED - Comments: FOUND DRAIN SHELF NOT DIRECTLY ON TOP OF 3 COMPARTMENT SINK AT MAIN KITCHEN. MUST RELOCATE. FOUND EXHAUST FAN NOT WORKING AT WOMEN'S RESTROOM AT LOWER LEVEL. MUST REPAIR/REPLACE. | 41. PREMISES MAINTAINED FREE OF LITTER, UNNECESSARY ARTICLES, CLEANING  EQUIPMENT PROPERLY STORED - Comments: FOUND LIQUOR REAR STORAGE ROOM AND SMALL STORAGE CLOSET BY BAR AT LOWER LEVEL CLUTTERED. MUST CLEAN AND ORGANIZE.",41.947359980046166,-87.65393244544859,"(41.947359980046166, -87.65393244544859)"
# 1990074,THE SHRIMP SHACK,THE SHRIMP SHACK,1939047,Restaurant,Risk 1 (High),6601 W ARCHER AVE ,CHICAGO,IL,60638,03/03/2017,Canvass,Fail,"18. NO EVIDENCE OF RODENT OR INSECT OUTER OPENINGS PROTECTED/RODENT PROOFED, A WRITTEN LOG SHALL BE MAINTAINED AVAILABLE TO THE INSPECTORS - Comments: MICE DROPPINGS (20) NOTED SCATTERED ON FLOOR ALONG WALL BASE IN REAR STORAGE ROOM WHERE  HOT WATER TANK LOCATED AND FRONT STORAGE AREA WHERE FURNACE AND BEVERAGE STORAGE NOTED. LARGE HOLE NOTED AROUND PIPE IN WALL NEAR HOT WATER TANK. SIDE ENTRANCE DOOR NOT RODENT PROOF, APPROX 1/4 INCH GAP. INSTD TO REMOVE ALL DROPPINGS, CLEAN AND SANITIZE ALL AFFECTED AREAS, SEAL HOLE IN WALL, RODENT PROOF DOOR SO AS TO BE TIGHT FITTING. LAST PEST CONTROL SERVICE RECEIPT 8/26/16. INSTD TO PROVIDE UPDATED RECEIPT. SERIOUS 7-38-020. | 30. FOOD IN ORIGINAL CONTAINER, PROPERLY LABELED: CUSTOMER ADVISORY POSTED AS NEEDED - Comments: PRE PACKAGED CRAB AND SHRIMP SALAD, POTATO SALAD AND PACKAGED CONTAINERS OF SHRIMP NOT PROPER LABELED. INSTD TO PROPERLY LABEL (NAME OF BUSINESS, INGREDIENTS, DATE, ETC). | 33. FOOD AND NON-FOOD CONTACT EQUIPMENT UTENSILS CLEAN, FREE OF ABRASIVE DETERGENTS - Comments: INTERIOR BOTTOM CABINETS IN REAR OF FRYERS NOT CLEAN, EXCESSIVE DEBRIS. INSTD TO CLEAN AND MAINTAIN. | 35. WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTRUCTED PER CODE: GOOD REPAIR, SURFACES CLEAN AND DUST-LESS CLEANING METHODS - Comments: GAP NOTED AT WALL AND FLOOR IN FRONT STORAGE CLOSET WHERE BOTTLED BEVERAGES STORED. INSTD TO REPAIR/SEAL PROPERLY. | 34. FLOORS: CONSTRUCTED PER CODE, CLEANED, GOOD REPAIR, COVING INSTALLED, DUST-LESS CLEANING METHODS USED - Comments: FLOOR IN PREP AREA WITH UNEVEN SURFACES. INSTD TO PROVIDE FLOOR SURFACE TO BE SMOOTH, EVEN, EASILY CLEANABLE SURFACE.",41.792138942200104,-87.78674847587374,"(41.792138942200104, -87.78674847587374)"

import csv
from collections import OrderedDict

DBA_NAME = 'DBA Name'
RISK = 'Risk'


def inspections_unsorted(filename):
    f = open(filename)

    inspections = {}
    row_number = 0

    # DictReader reads csv into a dictionary, uses row 0 field names for keys
    for row in csv.DictReader(f):

        # can print to help debug error due to messy input file
        # print('row_number', row_number)

        risk = row[RISK]
        if risk is None:
            risk = ''

        dba_name = row[DBA_NAME]
        # Python dictionary key can be a string or an int
        if dba_name is None:
            # go to next iteration
            continue

        if dba_name not in inspections:
            # not in dictionary, so add an array with it
            inspections[dba_name] = [risk]
        else:
            inspections[dba_name].append(risk)

        row_number += 1

    f.close()
    # print(inspections)
    return inspections


def inspections_sorted(filename):
    inspections = inspections_unsorted(filename)
    # convert dict inspections to SortedDict
    # sort by value number of risks, decreasing order
    # https://docs.python.org/3/library/collections.html#ordereddict-examples-and-recipes
    # http://stackoverflow.com/questions/613183/sort-a-python-dictionary-by-value (see comments)
    ordered = OrderedDict(sorted(inspections.items(), key=lambda t: len(t[1]), reverse=True))
    return ordered

